# version: '3'

# networks:
#   laravel:

# services:
#   nginx:
#     image: nginx:stable-alpine
#     container_name: nginx_be-yourself
#     ports:
#       - "80:80"
#     volumes:
#       # - ./src:/var/www
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - php
#       - mysql
#       - hot-reload
#     networks:
#       - laravel

#   mysql:
#     image: mysql:5.7.22
#     container_name: mysql_be-yourself
#     restart: unless-stopped
#     tty: true
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_DATABASE: homestead
#       MYSQL_USER: homestead
#       MYSQL_PASSWORD: secret
#       MYSQL_ROOT_PASSWORD: secret
#       SERVICE_TAGS: dev
#       SERVICE_NAME: mysql
#     networks:
#       - laravel

#   php:
#     build: 
#       context: ./
#       dockerfile: php.dockerfile
#     container_name: php_be-yourself
#     volumes:
#       - ./src:/var/www
#     ports:
#       - "9000:9000"
#     networks:
#       - laravel

#   hot-reload:
#     build: 
#       context: ./
#       dockerfile: hot-reload.dockerfile
#     volumes:
#       - ./src:/app
#       - /app/node_modules
#     ports:
#       - 8080:8080
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     networks:
#       - laravel

#####

version: '3'
services:
  php-fpm:
    container_name: php_be-yourself
    build: ./.docker/php
    volumes:
      - ./src:/var/www
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql_be-yourself
    # command: --disable-partition-engine-check
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_be-yourself
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel
    links:
      - php-fpm

networks:
  laravel:
    driver: bridge

# volumes:
#   db_data: {}
